apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:feDCGRlKDkash+RyGLpB3I7cP1H3JaMPi4uOyG/RBYAm7u4lG+JbUA==,iv:BztRojMFgMozu2YKBCHxutN2oXNyvoXBPFK0Ow5pCbQ=,tag:KCTNu7OUE7a4ZhHOqVVEug==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1zfv0dcgrmyqcnatthxn9qfnang6pk3hz96z93wyd792u8vncc3sqea5udt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhT3NFdUh6Q0sxTThmVTNY
            K0d3VS9STDVWdkJ0YWJZWGp1T2NNY1Buem5BCjVqQTh6QUU0SHgrYmJXNExmNG00
            WitMd2NzT1FVU043Sm9ncFU0T1NwVVUKLS0tIFR3eG0yQU1qTmpJL2hySm8zcDh0
            aE9jdEpybFppK1RPaUNGYkpwRTcrU2cKun9z6OsKoHVXEKR50yKN8+NYjU9Vd8N2
            TE45hL7zUSpndSdg0YaZGA8Q/oL3bzMkZ06Uu2vOKNHCcEfwA3qNUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T22:05:14Z"
    mac: ENC[AES256_GCM,data:VNE4g8XsOiiBnRxfmPHu6xcsLph9Gzmq/N5PIfMilLyif7NHJlXTf0KaG7SXUnVNUlgM9JKrOkxZjRKTvH2ZiiccvMSfegVwTU5uhgOQNr0IGr47pFO6s7vu34J1Dv9wGOzmNDrRqTMYqCcH74Zzvo7Bwb/J/78t0OPhkTZiG7A=,iv:2xxsL3kIAXJ9G/Z/35S7IJg+63CrGLYAdqln7spGOYU=,tag:7Y1E3oO0NeSkdEjnrrlhaw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
