apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:URqhR2s/wqV1zzU23FEXUNnogi1kSW+7fOhWgaLSLAzk4cVPekPfaA==,iv:XLk3mq6VUI7X+PEZqud7p/sD0Y+/3PJiqdoK0rzeO1g=,tag:w3DakwoJ59LcwdNkZXlHPQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1zfv0dcgrmyqcnatthxn9qfnang6pk3hz96z93wyd792u8vncc3sqea5udt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZEdkdFpSSnZhbk5kRnhK
            bzFsQzllVFNtV3FvSzNYd1ZyZHBCekdLMnhJClJoTnE4RzdWN0l4bFpMdG04WTJT
            WkFRYS9wbW0vWVJJcGJmenRPeE9tTjQKLS0tIGliNVdnVDNxRE9OdmJlUlcxRWhr
            cnVDeDE0UEVKVS9ZRlYrRzBSN0xZbmsKgHOJmIopnuMFuDXpP2nBECBPMH/+d5AF
            Wo9kxtGXUg1p0mJSZPVFdwuSnkubHoxA024FfKTKTfw8+J3bcU6uAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T13:20:46Z"
    mac: ENC[AES256_GCM,data:pLOjnMW8WNniBMMnAmeLakyV0opet/9lnf9oBL9lXqLOtFYCkPoMcd6xfUqBo+9wENjr++eXq2cAw8UpyI8zE0jhR9SC8UTQIqMUQDBglGsk1fLrL4IN2ivxh8eVPxUc/joB290lipDHfQuFLs5sIuwFSNJ4N6QQzqtb2r+JjMY=,iv:UaK6HO62+qsCqAXNmKnRYgspKFa1PXJ1KJaUUyp+axI=,tag:fF+XvzfIcmSBZNioC6zKhg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
