---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: filebrowser
      version: 12.12.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      reconcileStrategy: Revision
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                FB_NOAUTH: noauth
                FB_ADDRESS: ""
                FB_BASEURL: ""
                FB_DATABASE: "/database/filebrowser.db"
                FB_CONFIG: "/config/filebrowser.json"
                FB_ROOT: "/data"
                FB_PORT: "{{ .Values.service.main.ports.main.port }}"
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: 'true'
          traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic@kubernetescrd, traefik-auth@kubernetescrd
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: files.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        mountPath: "/data"
      stash1:
        enabled: true
        type: nfs
        path: /mnt/media/stash/misc
        mountPath: "/data/stash1"
        server: 192.168.50.118
      stash2:
        enabled: true
        type: nfs
        path: /mnt/media/stash-rm
        mountPath: "/data/stash2"
        server: 192.168.50.118
      media:
        enabled: true
        type: nfs
        path: /mnt/media/mediashare
        mountPath: "/data/media"
        server: 192.168.50.118
      books:
        enabled: true
        type: nfs
        path: /mnt/media/calibre
        mountPath: "/data/books"
        server: 192.168.50.118
      docsconsume:
        enabled: true
        type: nfs
        path: /mnt/media/filing/consume
        mountPath: "/data/docsc"
        server: 192.168.50.118
      docsstore:
        enabled: true
        type: nfs
        path: /mnt/media/filing/store
        mountPath: "/data/docss"
        server: 192.168.50.118
