---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/provider-notification-v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  address: ${DISCORD_ALERT_WEBHOOK}
---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/alert-notification-v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord
  namespace: flux-system
spec:
  summary: "Flux Events"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: "*"
    - kind: HelmRelease
      name: "*"
      namespace: authelia
    - kind: HelmRelease
      name: "*"
      namespace: blocky
    - kind: HelmRelease
      name: "*"
      namespace: cert-manager
    - kind: HelmRelease
      name: "*"
      namespace: cloudflared
    - kind: HelmRelease
      name: "*"
      namespace: cloudnative-pg
    - kind: HelmRelease
      name: "*"
      namespace: clusterissuer
    - kind: HelmRelease
      name: "*"
      namespace: default
    - kind: HelmRelease
      name: "*"
      namespace: external-dns
    - kind: HelmRelease
      name: "*"
      namespace: external-service
    - kind: HelmRelease
      name: "*"
      namespace: flux-system
    - kind: HelmRelease
      name: "*"
      namespace: freshrss
    - kind: HelmRelease
      name: "*"
      namespace: gatus
    - kind: HelmRelease
      name: "*"
      namespace: generic-device-plugin
    - kind: HelmRelease
      name: "*"
      namespace: grafana
    - kind: HelmRelease
      name: "*"
      namespace: homepage
    - kind: HelmRelease
      name: "*"
      namespace: kube-node-lease
    - kind: HelmRelease
      name: "*"
      namespace: kube-system
    - kind: HelmRelease
      name: "*"
      namespace: kube-prometheus-stack
    - kind: HelmRelease
      name: "*"
      namespace: kubernetes-dashboard
    - kind: HelmRelease
      name: "*"
      namespace: kubernetes-reflector
    - kind: HelmRelease
      name: "*"
      namespace: linkwarden
    - kind: HelmRelease
      name: "*"
      namespace: lldap
    - kind: HelmRelease
      name: "*"
      namespace: longhorn-system
    - kind: HelmRelease
      name: "*"
      namespace: mealie
    - kind: HelmRelease
      name: "*"
      namespace: media
    - kind: HelmRelease
      name: "*"
      namespace: mend-renovate
    - kind: HelmRelease
      name: "*"
      namespace: metallb
    - kind: HelmRelease
      name: "*"
      namespace: metallb-config
    - kind: HelmRelease
      name: "*"
      namespace: openebs
    - kind: HelmRelease
      name: "*"
      namespace: snapshot-controller
    - kind: HelmRelease
      name: "*"
      namespace: snippet-box
    - kind: HelmRelease
      name: "*"
      namespace: speedtest-exporter
    - kind: HelmRelease
      name: "*"
      namespace: spegel
    - kind: HelmRelease
      name: "*"
      namespace: system
    - kind: HelmRelease
      name: "*"
      namespace: system-upgrade
    - kind: HelmRelease
      name: "*"
      namespace: tailscale
    - kind: HelmRelease
      name: "*"
      namespace: traefik
    - kind: HelmRelease
      name: "*"
      namespace: truenas-exporter
    - kind: HelmRelease
      name: "*"
      namespace: unpoller
    - kind: HelmRelease
      name: "*"
      namespace: volsync
---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/alert-notification-v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord-error
  namespace: flux-system
spec:
  summary: "Kustomization Error"
  providerRef:
    name: discord
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: "*"
    - kind: GitRepository
      name: "*"
    - kind: HelmRepository
      name: "*"
    - kind: OCIRepository
      name: "*"
