apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:Jn808NXqU5GP+3cSGvtRPKkvJrM+QTSzaK9zfA3KinZ3r/FFTYqA99TfR1ebJ9tWerZu4eh5Ishyqs1WmOi27XIBrAiFFCSbw9Rbm9LCYyo9LJVJPeP7wMxzvUASiY2WsvSluEY+JKadPH/btLdHtxrUBRT8OfHtQA==,iv:UZbZBzVd/B6YjvjObqClhDMz8i5W8joCVw4KPiwGvtU=,tag:6RWlu8G7EvTSZFhy7IUDAQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1zfv0dcgrmyqcnatthxn9qfnang6pk3hz96z93wyd792u8vncc3sqea5udt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbDg0SDFwQ3FYN00ycXNv
            S0VnejUyQU5hWUpYZGR2NXptdmpxdldoNkRFCnBhQ3dlK3dSWnVyNzNvaEJzbWpZ
            d2diUXVVQ2RrUW5hYk8yNTBzK0xjNTgKLS0tIDFXWnhwZ1hPUEJ3d0N1bEhJVzdh
            WkNyYmREVHVwTGRUTklHalVUdkJCMXcKM6mnJB4i2PPcV+be/Mx5pV+Pe5oSgoC0
            Ey9ktrCDMNuwd6OK0wcxzilS2fhX/ocE3cl8t/5vPEfeqcDo6mnPrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T11:46:23Z"
    mac: ENC[AES256_GCM,data:fz3/AbNoh1fsX4jNjdhardM68owDGKonHVSXOkHStJYoiVrYkMa0NXAENWRcb3cSEbup8BN17/B51FKvNxYK8+5JeYtlUYDTu0a1t6TUoAgCRL/rMKlp9dYZX7y7nRZC1FrrAYl5uI36P/fHydw6i1eC06kX1Q/1brMix5aGZl8=,iv:zVq77VVbEQZ+tkkCSJISlrXCXBwQ6QoeTrU9MUbZQmA=,tag:XmK3DAo/t7byLdq2zPxdzg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
