apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:+fHPIa0lXkUZS6sV7QqJLK2lx9zXf9gefJY0nB4w7B3Vsrulsa/1JmoinrGfGbAVarVid4FhjqgWS0cj/x8fqMuqxJoJtJMC0qd1L5jvQ3VxRnHm9gyrsaJbFaEras5cnEEZRIWkx97i4TAEUN1wRZuUFcV17hRqsw==,iv:axFo18Htb25b0lir/5XBlYAsef0Acv5bsCYUTauXbjs=,tag:8lFwDi96FGsvQjZF7iFH/w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1zfv0dcgrmyqcnatthxn9qfnang6pk3hz96z93wyd792u8vncc3sqea5udt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBM2Y4SDRtclZ0d3JXWHN0
            OEJqSm1DbHA0TDJabGh2cHFobW1hWHJXclRJCmV1QVpuV0lYTmhKVE1IWEFXV29h
            MURnZEdBWUpwNEFTQXZLQXdaZVhJRGcKLS0tIFZ0NFI3ZDZiK0krYmEzRUpRSlpi
            UVd1eGhUa0h5ZGpyZDRQU3RUU0lCU2sKBlSaefMjvy9YL9Lm1r2CDvU2qgVS2sau
            WFq6BYXmHg4pJK7sHWSGOI8cAJ5n8m2sFzJC8SVrbhkajpsCbzsnKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T13:13:24Z"
    mac: ENC[AES256_GCM,data:hJu7JRXuRnaR1rrpPj0bflkPcOjHSxJHkllSJGt6g5ID4a8VcWgiM3DUu2MVszzWJLYWlg7uj65/3qsCnAU3vuU7O09L5m3BkobfhDSHzp2pPzsyQb1+5Z6R5zxaLAsTAD5nMt70HPt9jPM1FuAlejjp831wge4MSB/jhfFOTx8=,iv:wv7vfCj6hdnPgdmWlVCOoPrgNJoW/vxDMqhl7IHSHKE=,tag:Ippf+3elkbBzLfAPpw379A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
