apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wFZSxz8MU0kspL0TarQ2X7L6DqPZY6ukYPXf31cv/qH47tyaDwjWWl1HODDp3i0wNFNxMXbih1KbxkSRv+yKmFf9l4LGVtTO02dBBp/M0CrdecT6KSeogQPmfGAzcYxT+RRBMW3b5Uiyzec5AGW44XPw1+l+D/yeZs2BUZOdVCym4u/GErXZrZk2Sodsl4cr71zlW5cG7QDe6zRgLyVdobQ3q5dOtww3ZiOE+CMsmrIxbOcjcxwQL36i14JdqiSJO2P9xCf683Ktk22uXQtJWKQx1Eareo4G+lEGaIMbyV2oJmaLbsrryWFtf0nbaJRkQSXASujyt0LU5Ar6hPC4cvUug6WvXUV4hpAxLT86WqvntkTQHw+Ssi8TY2MHidyD,iv:8KL8XxyHxn/rlV2nTR5U57hJiIdLkX+BkKjGDIg6XWg=,tag:3ltRBxHM1SpG/JWrI2Q8ig==,type:str]
    identity.pub: ENC[AES256_GCM,data:wXPket+1aqm1Z35z6mhEIhZF56GzVyjWcp7U61BTx4YQ7K/T+r/WoKyiRINebZPBXwtZhCjOOEX3ZKcoAcqj+TLR5x72zwy2QjzflfUI9zY0rv8+anbi0+gIj2QZOe3v5eRwLq8wlTyAzqN239MkHS24xArhqEQS+0X/PUsenlXgMS79L6wDsSEn9YbvUk9yAgeFBlbaktcHdJFaE6aAjDFyGCTgSRYsD1d1r9yLK8G79XIWutkRKfIYRbl9g5qeP6q4hNDlhZug8Jj8SA==,iv:OEz2uXaaMi6ScpOobddOfOPu1H5cqhaN2re1Z/HWSt0=,tag:CBt6W5LT2RF05pYAbWDSfQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Jb6SW4VY7nDqRncvzV3G3CoeURSNueHmDJ8qVWr4dccqs3leb6zdTm3ctt7UIEXaylPmivyyGAs27r9ozCUCqY6IJ5N94U4syj1ep1TR4hFbEzbftopywPTZs+sZjF/C8TI3aYD4vZw7tUmr2MngTFgVh4sd3T3lzCSOFvlS4scpbqlzw6xyXaqkooWr2zcPJ0pswCk4/BSQt+kMdsjC6naB3ypwdbYL6BI+,iv:lrAnQKci5hlAK3cU0xHJN7usYf5EwoKYiYwc5cpBxDA=,tag:Oie9O7jW3kianP8+BeU/TA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1zfv0dcgrmyqcnatthxn9qfnang6pk3hz96z93wyd792u8vncc3sqea5udt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRjA1bnQ5N0crMDRvQ2xr
            elZ1VWMwSm5pY0l4SS83Qm1NWVhZY0VidURNCnNXQmpqemROOGtFa0dzSjRrMEEw
            WFEvQm9jeDQycThIMGVrSmVOdVl0NGsKLS0tIFpqT2d2cURtUTdGNVVnS2VPZ2Fr
            b29ZcUhqMERoMDdSODFHekdLNmc1b3cKCwBRu7Zcydmwf3nKLrmteuOT10jmUEC6
            ESGkn789sFbzk5R+ZPCcRIngAq6Iy+epbr/I8786H4pBauBRAtrGeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T11:46:23Z"
    mac: ENC[AES256_GCM,data:qWgothimAgwj7pil5s1AGegxCMtf0EPh0UGaylQX/cATH+UgxgzF4xwmawYpRnQYf2lbMa0kDaENOMm3/lk0xaJhmfvDWGOggw9n7Hwiqi9jM4PaKjp+cnQpFvEnbe634Xij3S1fPzE7ErSb+GJ0wGTMcL7BO6Edxq/wL/70knc=,iv:oplPNkS1u4jN7NRrCzeVOAupWDmo1hANq3yfbd5NGBE=,tag:AY30P6Rm20hVQbbEbCDhvA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
