apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:B0XjIc5V2vaJ7CJO9KitmqLn55vjM14gIupFzcgX3gn+4rlCM6B1KFQ/d+t9o2dSchTfCGGYSaziTkzZH9j63b5ELYXhL6R1S0f+qeyuBcfZaePhqRkJxQFYM/ie24a2j+NKctP30SJUaFnL1t5z6E2FpOsBePhySJKysd174wi1Uym25JbZYkshadpQTOT8u6Sz7+7S3bxWcZPHndgOltPGQT5mzJeCobozgMtb9xXaS2bQB0eictZRKvUtm8buIvopIqBpY4W7bnibKPF9NaDZKBLlCOQjgXbFq1i88NbwPywtEm+PDoJx2L1GgFDZ7qrwouSlvsuGcitTl0ArtlhG6Gix8xMxkBivQivwFSDvJgp8dA9qFUA4KhRqDprA,iv:+HkqFg0IB1ddc2x9clGR6w0wJnPLTOMp2iZj3+GvBug=,tag:E48m4vxIwljTW++E5xRymQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:UWVJQXjGXHX9V3nYCwhnFTxgrBx/dWt9wQv0FkMzS1GLuaITFI8EEU+WUZcmHVvkVokac7KGjHkleoqar6e6dg5HxTLylFmJGbvul2/BwDt//h2Pj3a6ktmrZQTEW48qKlMpmDMucS/EoDIO+JTi+kldXt+5gTZxUoIzFLc2SdDpZ/BaY36wv1jUf11MkWlaIDpf0C5p3YrU0HoqMT7JMceoqla3FFFIMJmqXmPt5BvkRpdEf12JUIHtlh6otfqQx9G5FZwbqjPoBJdLyg==,iv:D4O0AYj7uFlhzYy9uQfdUA9XmJwTkXCrDcGUQ2YMI30=,tag:gFBisJrP1EAS3gFCtYoV6Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:MyKIGyQ/OB51517RK2zc+gmgbGD8EW3X+duAvzOfbO3OTlmmoIHojLTMZvh5lowcLT/XW7uAOEb1cRezV5xwEV3+JAKL9wpCgqyX7FF9ZoxRddJD/AxwRRnZt416o+5mhs6ZhSvZCvAFnvozMYTco4eMIgkopPXnuLPt8hISYvuLB6b+UAuGJAJaIguhoBVZMPFUlGE098wN9RxdxIePcMrqg0rpXhvwN/1q,iv:abUBJ55PgdUnE2argOFNntRu2EmfHvDr3V1Z+mlzJVQ=,tag:XZ3h/K58HIo4dtl0sFF6gQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1zfv0dcgrmyqcnatthxn9qfnang6pk3hz96z93wyd792u8vncc3sqea5udt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaVc4akZEa2RrR0dueUFr
            QXBRb2dHNEh5ZHhlQzlYYm9aazRITVY3NTFFCjYrbXhiYlczL0dSbFpkeXQ3d3NG
            SWYycHJCUzQyaUlIY1IvVHhIOU9mQ3MKLS0tIGsxaGhnZEgvcnVVRGdtVHFwNmlH
            STNoMnpBVHEreXFIZ2l0N211UGZpZTAKNLr9NZSIp5gOLbgMMgqQD9yMyyVopo7T
            7ouawcrF+d2DAanLQ41Lt8cTTXxSlF+WAkGqPKflPxZ8ueMCZ5jSHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T05:54:26Z"
    mac: ENC[AES256_GCM,data:8gnR75Jfkyx1N3ZqyEhxj1BDIzx2W4FqOEh2xOyweis8E6vJVLrt+I//zI9vZET8PAaxfGOEcdo3bJoljlqT5eT/4KzJ0bFOYpzgZE8PTtI9dLl0FqE2S7TgRiXAYhpZvERbbZMZXIF/mJa54x4iImH9adnlGlwJUCvaTvr2ep0=,iv:eJXIvxJ7qOsiV7WDFYH2NbR0TCcCf7OcojBknfsejn8=,tag:pOAHlXRzpgYhwic4d+gTMA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
