apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:doybAZBlVOz+W0nOGM93lhItrm3brZ0rPKm5qgG4fzee6JZMZUc9UgVJf1JUBo6knJHfzeB4Xpg8lB+RV0YN4hfU/3gQOYSjIxfI1CsYUjhD3/nJ25zrHOqfGChwj1IQcT3eYmvdSh+GVar3+LubLjLwlc+VyZrOmxV/bINOHPSqJHLjIq3KSZK7JTyOVVCDBmPp9nvyPHWbYIUVwRdiuoEU49rblb5yL1TKxiA+DtI1b+kBLDr0fTOi6PGE1Rv54pBhNBPrhrMnSDMEn7aL4hOf9+ojQai0gDV4c4yBBeqXSjH4qpFD6RhwU1ZkZX/B9W4yTQfwhEhC7FPEUJCS513i3eM30nDQ6fQ5/PNB4XVqOA5hCetYo2LMZzThcZ/7,iv:91kFWlf6DuKIBESQjPhi7ZDL5gr8Kemp6MskLZZSbLo=,tag:JTEc2nkf6NviDN+Oqn5Y7w==,type:str]
    identity.pub: ENC[AES256_GCM,data:cBCjzJ3b6upW4L+kcDIXgkJl+ea5NqIxXbsYHZFGJRPqDGcpYK868fQ8OD1Li3+ym6VPBqIP4gA2nXx8LBhEMOVwGlzH9qgR4RRfCiGiamdCcwWaXCBSEC/FSGVkmE3CheE1x7iBqt12tGEKGaQ6ryCfPYQqax6riLgNud95NL2eluOqqiZpd1iIicS88/lu9bppJmqHAi1uPl5tUfafFoy7f/v9Z54z4kQdnO/+rJ1HUmzyOv3d961GSnaYzKI+OBtOGrEZyC84J9suVw==,iv:A8wE0ad0PIKCtexfkbjElW82Ga1le1b12vjt8Qdq//0=,tag:gDbmgLHv0TRNSi2IZ6mFBA==,type:str]
    known_hosts: ENC[AES256_GCM,data:mCuXR/t0Zi1SGnMRUC47F/x5T7f2As+tADVLvSBW78HfKXzRhmclL0Td2mrYjgfN1/PWKJPH7Va+uhawLRCQFlATutp31f8A1FihRcBNOpGNTmwfhTDF97+d5PcglUrSXNRZ8e5zHuOdmY05pRXtj5FmRJvQWSNo619QNNi97NcnazC/sto8RWwbgZLxEiLtL/eMWZfx4Mbdtii3aIFDr9BWprNlQnEOIFIK,iv:96js1f/8HPy2yN7lAcT1z56q/SJgK68KELZ0u8oxNp4=,tag:f5/SNZDmP7KkMbI64qMdNQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1zfv0dcgrmyqcnatthxn9qfnang6pk3hz96z93wyd792u8vncc3sqea5udt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTFlTRFJTUkFIak1ETEkw
            YlM0K2pzamg0RXY2VVMycnNkdnI5VHdxbndVCmd0RTJUdm5TSWdwNDhPRExEL1F1
            WmtNa2dzcFF2NzR6a0RpNnpqT1FNa1EKLS0tIHZvbFkwQk1HZ25pNXJUU2pFcytQ
            ck0vUDdQVHNFVkl6MUoxY0E1OHlpS0kKT9XFmS3TCiMkUKQSdFMeL49IKSrPcLeb
            jybOPwPQLaj/pp5XyEMUb9Fsrj9o3DetZwQtfDXtWaYQeqtl2sercQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-26T05:02:19Z"
    mac: ENC[AES256_GCM,data:YBBExRw+MIl6N0p7RJSUk7PQ5Et87614cjrpmZ0K0v1m+DBk7d1j36wpn66mUCRjjEoIqoW4k3kITq5cadS/eGLfLR02D2NpDRKsJhxLRivtNJa+2E7R+X45YFUGzcPPqtGAwsrEhpLaaoQZE8P6Xv3ocE2oxKPVMqdn7s0BVyE=,iv:TB0YmMv1x46NNti0vvQfclbnFcp+AsYLR//c/ujdA8Q=,tag:qyl9aEq1hRPpRy9TUYqgrw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
