---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/MaverickD650/home-ops
  provider: github
  ref:
    branch: main
  secretRef:
    name: githubapp
  ignore: |
    # exclude all
    /*
    # include flux directories
    !/clusters
    !/repositories
