---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/provider-notification-v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-status
spec:
  type: github
  address: https://github.com/MaverickD650/home-ops
  secretRef:
    name: github-status
