---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stash2
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: stash
      version: 18.12.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      reconcileStrategy: Revision
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-stash2"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: 'true'
          traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic@kubernetescrd
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: stash2.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    gatus:
      endpoints:
        - name: Stash 1
          group: Media
          url: "http://stash.media.svc.cluster.local:9999/"
          interval: 1m
          ui:
            hide-url: true
            hide-hostname: true
          conditions:
            - "[CONNECTED] == true"
          alerts:
            - type: discord
              description: "healthcheck failed"
              send-on-resolved: true
    configmap:
      gatus:
        enabled: true
        labels:
          gatus.io/enabled: "true"
        data:
          config.yaml: |
            {{- $.Values.gatus | toYaml | nindent 2 }}
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      cache:
        volsync:
          - name: cache
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      generated:
        volsync:
          - name: generated
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      metadata:
        volsync:
          - name: metadata
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      blobs:
        volsync:
          - name: blobs
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      data:
        volsync:
          - name: data
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      store:
        enabled: true
        type: nfs
        path: /mnt/media/stash/misc
        mountPath: /store
        server: 192.168.50.118
