---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 19.10.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
      reconcileStrategy: Revision
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                GF_SECURITY_ADMIN_USER: ${GFAUSER}
                GF_SECURITY_ADMIN_PASSWORD: ${GFAPASSWD}
                GF_AUTH_GENERIC_OAUTH_ENABLED: true
                GF_AUTH_GENERIC_OAUTH_NAME: authentik
                GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ${GFOAUTHCID}
                GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${GFOAUTHCST}
                GF_PANELS_DISABLE_SANITIZE_HTML: true
                GF_SERVER_ROOT_URL: https://monitor.${DOMAIN_0}
                GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email offline_access
                GF_AUTH_GENERIC_OAUTH_AUTH_URL: ${GFAUTHAURL}
                GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ${GFAUTHTURL}
                GF_AUTH_GENERIC_OAUTH_API_URL: ${GFAUTHAPIURL}
                GF_AUTH_SIGNOUT_REDIRECT_URL: ${GFAUTHSOURL}
                GF_AUTH_OAUTH_AUTO_LOGIN: false
                GF_AUTH_OAUTH_SKIP_ORG_ROLE_UPDATE_SYNC: true
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: 'true'
          traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic@kubernetescrd
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: monitor.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    configmap:
      dashboard-provider:
        enabled: true
        data:
          provider.yaml: |-
            apiVersion: 1
            providers:
              - name: sidecarProvider
                orgId: 1
                folder: ''
                type: file
                disableDeletion: false
                allowUiUpdates: true
                updateIntervalSeconds: 30
                options:
                  foldersFromFilesStructure: true
                  path: /tmp/dashboards
      gatus:
        enabled: true
        labels:
          gatus.io/enabled: "true"
        data:
          config.yaml: |
            {{- $.Values.gatus | toYaml | nindent 2 }}
    gatus:
      endpoints:
        - name: Grafana
          group: Metrics
          url: "http://grafana.grafana.svc.cluster.local:3000/api/health"
          interval: 1m
          ui:
            hide-url: true
            hide-hostname: true
          conditions:
            - "[CONNECTED] == true"
          alerts:
            - type: discord
              description: "healthcheck failed"
              send-on-resolved: true

    cnpg:
      main:
        cluster:
          singleNode: true
