---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 20.7.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      reconcileStrategy: Revision
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    plex:
      serverIP: ${PLEX_IP}
      additionalAdvertiseURL: "https://plex.${DOMAIN_0}, https://plex.${DOMAIN_0}:32400"
      disableGDM: false
      requireHTTPS: false
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-plex"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PLEX_CLAIM: "${PLEX_CLAIM}"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IPC}
        integrations:
          metallb:
            enabled: false

    gatus:
      endpoints:
        - name: Plex
          group: Media
          url: "http://plex.media.svc.cluster.local:32400/identity"
          interval: 1m
          ui:
            hide-url: true
            hide-hostname: true
          conditions:
            - "[CONNECTED] == true"
          alerts:
            - type: discord
              description: "healthcheck failed"
              send-on-resolved: true
    configmap:
      gatus:
        enabled: true
        labels:
          gatus.io/enabled: "true"
        data:
          config.yaml: |
            {{- $.Values.gatus | toYaml | nindent 2 }}
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: 'true'
          traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic@kubernetescrd
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: plex.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
            src:
              enabled: true
              trigger:
                schedule: "0 1 * * *"
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
      stash1:
        enabled: true
        type: nfs
        path: /mnt/media/stash/misc
        mountPath: "/data/stash1"
        server: 192.168.50.118
      stash2:
        enabled: true
        type: nfs
        path: /mnt/media/stash-rm
        mountPath: "/data/stash2"
        server: 192.168.50.118
      media:
        enabled: true
        type: nfs
        path: /mnt/media/mediashare
        mountPath: "/data/media"
        server: 192.168.50.118

    addons:
      codeserver:
        # -- Enable running a code-server container in the pod
        enabled: true
        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: 'true'
            traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic@kubernetescrd
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: plexedit.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
          tls: []
